r"""Apply a list of prop placements to a region, for the AT3 launcher's PROP EDITOR.

Reads a CSV of placements and inserts one new object record per row into
`lm_level_<region>.lvl`. The mechanics are in OBJECT_SPAWNING.md; this adds the
catalogue and the residency check on top.

    Prop,X,Y,Z,Yaw,Pitch,Roll
    Civilized Treasure Chest,47.37,91.98,38.22,0,0,0

Every run reverts to the backup first and re-applies the whole list, so the CSV
is the single source of truth and repeated launches never stack duplicates.

TWO THINGS DECIDE WHETHER A PLACEMENT IS VISIBLE (see OBJECT_SPAWNING.md):

  1. the zone index at +20 must match the position - handled automatically,
     read off the records already standing at the target
  2. the prop's geometry must be resident in that zone - which is what the
     catalogue's `residency` field is for. Props in the level's "normal" bundle
     are not zone-gated and work anywhere. Props under \data\instances\<area>\
     live in one zone bundle and only render in zones whose zonedep lists it.

    python place_props.py 01 --csv props_01.csv
    python place_props.py 01 --csv props_01.csv --check
    python place_props.py 01 --list
    python place_props.py 01 --revert
"""
import argparse, csv, math, os, re, shutil, struct, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from spawn_prop import (ROOT, TOKEN, SENTINEL, CHAIN_START, NEXT, CLASS_ID,
                        INST_ID, ROT, POS, ONE, TINT, NAME2, ZONE,
                        lvl_path, u32, walk, pos_of)

BAK = ".propsbak"

# Only props confirmed in game go in here. `key` is the dword every placement
# carries at +104 - the prefs hash for the chest, the geometry hash for the
# barrel, which references its geometry directly.
CATALOGUE = {
    "Civilized Treasure Chest": {
        "key": 0x3BE028EE,
        "asset": r"\data\geometry\Collectables\civilized_treasure_chest.geo",
        "residency": None,          # "normal" bundle - every zone
    },
    "Rupture Farms Barrel": {
        "key": 0x2443E6AF,
        "asset": r"\data\instances\town_01_1\geometry\decorators\destructible\rf_barrel.geo",
        "residency": "zonebundle_87.smb",
    },
}


def library_reach(region):
    """key -> None (every zone) | "?" (unknown) | set of zones.

    Generated by prop_library.py. Without this the residency check only covered
    the two hand-written CATALOGUE entries: every placement named by raw key got
    residency=None, which means "not zone-gated", so nothing was ever warned
    about. Placing 200-odd objects that cannot render in the target zone
    produced no output at all.
    """
    p = os.path.join(ROOT, "StrangerAT3", "RegionData", "proplib_%s.csv" % region)
    out = {}
    promoted = set()
    lp = os.path.join(ROOT, "StrangerAT3", "RegionData", "promoted_%s.csv" % region)
    if os.path.exists(lp):
        with open(lp, encoding="utf-8-sig", newline="") as f:
            for r in csv.DictReader(f):
                promoted.add((r.get("Bundle") or "").strip())
    if not os.path.exists(p):
        return out
    with open(p, encoding="utf-8-sig", newline="") as f:
        for r in csv.DictReader(f):
            z = (r.get("Zones") or "").strip()
            try:
                k = int(r["Key"], 16)
            except Exception:
                continue
            # A bundle promoted to `normal:` by promote_bundle.py is resident
            # for the whole level, so anything inside it reaches every zone.
            if any(b.strip() in promoted for b in (r.get("Bundle") or "").split(";") if b.strip()):
                out[k] = None
                continue
            if z == "*":
                out[k] = None
            elif z == "?" or z == "":
                out[k] = "?"
            else:
                out[k] = set(int(x) for x in z.split(";") if x.strip())
    return out


def blockmap_txt(region):
    return os.path.join(ROOT, "data", "bundles", "region_" + region,
                        "lm_level_" + region + "_blockmap.txt")


def zone_deps(region):
    """(zone bundle names in order, zonedep list per zone)."""
    zones, deps = [], []
    p = blockmap_txt(region)
    if not os.path.exists(p):
        return zones, deps
    for line in open(p, encoding="latin1"):
        line = line.strip()
        if line.startswith("zone:"):
            zones.append(line.split("/")[-1])
        elif line.startswith("zonedep:"):
            deps.append([int(v) for v in line.split(":", 1)[1].split()])
    return zones, deps


def matrix_from_euler(yaw, pitch, roll):
    """Row-major 3x3. Z up, yaw about Z, then pitch about Y, then roll about X.

    yaw alone reproduces the pure-Z form that 141 of region_01's 148 spawns
    use, so leaving pitch and roll at 0 matches the game's own convention.
    """
    cy, sy = math.cos(math.radians(yaw)), math.sin(math.radians(yaw))
    cp, sp = math.cos(math.radians(pitch)), math.sin(math.radians(pitch))
    cr, sr = math.cos(math.radians(roll)), math.sin(math.radians(roll))
    return [
        cy * cp,  cy * sp * sr - sy * cr,  cy * sp * cr + sy * sr,
        sy * cp,  sy * sp * sr + cy * cr,  sy * sp * cr - cy * sr,
        -sp,      cp * sr,                 cp * cr,
    ]


def resolve(prop):
    """Catalogue entry for a prop identifier.

    The launcher's library lists every placeable object in a region, and retail
    data gives almost none of them a recoverable name - only 87 .geo path
    strings survive anywhere in the install and none are region_01 props. So a
    placement may name its object by raw key instead of a catalogue name.
    """
    spec = CATALOGUE.get(prop)
    if spec is not None:
        return spec
    t = str(prop).strip()
    if re.fullmatch(r"[0-9A-Fa-f]{8}", t):
        return {"key": int(t, 16), "asset": None, "residency": None}
    return None


def donors(d, recs, extra=()):
    """{prop name: (offset, length)} for every known prop present."""
    wanted = dict(CATALOGUE)
    for name in extra:
        if name not in wanted:
            spec = resolve(name)
            if spec:
                wanted[name] = spec
    return _donors_for(d, recs, wanted)


def donor_near(d, recs, key, target):
    """The instance of `key` CLOSEST to `target`, as (offset, length).

    THE DONOR'S LOCATION DECIDES WHETHER THE CLONE IS LIT.

    Baked lighting is positional: a placement carries lighting belonging to
    where its donor stands, and a clone dropped far from that spot renders
    impossibly bright instead. Measured across six regions, native placements
    that copy no files at all:

        donor 34, 54, 41 units away  ->  lit
        donor 91, 140, 295 away      ->  unlit

    Zone agreement does not predict it - region_02a lit with a donor in a
    DIFFERENT zone, region_04 came out unlit with the donor in the SAME one.
    Distance does.

    _donors_for picks the shortest matching record, which is arbitrary with
    respect to position; that is why three regions happened to work and three
    did not. Choosing per placement, by distance, is the fix.
    """
    best = None
    for s in recs:
        e = u32(d, s + NEXT)
        if e - s < 108 or e <= s:
            continue
        if u32(d, s + 104) != key:
            continue
        q = pos_of(d, s)
        if q is None:
            continue
        dist = math.dist(q, target)
        if best is None or dist < best[0]:
            best = (dist, s, e - s)
    if best is None:
        return None, None
    return (best[1], best[2]), best[0]


def _donors_for(d, recs, wanted):
    """{prop name: (offset, length)} for every catalogue prop present."""
    out = {}
    for name, spec in wanted.items():
        best = None
        for s in recs:
            e = u32(d, s + NEXT)
            if e - s < 108 or e <= s:
                continue
            if u32(d, s + 104) != spec["key"]:
                continue
            if pos_of(d, s) is None:
                continue
            if best is None or e - s < best[1]:
                best = (s, e - s)
        if best:
            out[name] = best
    return out


def _parked(d, recs):
    """Positions shared by 3+ records: template records, not world placements."""
    import collections
    c = collections.Counter()
    for s2 in recs:
        q = pos_of(d, s2)
        if q is not None:
            c[tuple(round(v, 2) for v in q)] += 1
    return {k for k, n in c.items() if n >= 3}


def zone_at(d, recs, target, k=12):
    """The zone the records around this point belong to.

    Polling the nearest records only works where those neighbours are real
    world placements. Region_00's spawn has NO real geometry nearby: 28 records
    sit stacked on (0,0,0) carrying contradictory zones - 11, 2, 5, 7, 6, 9 and
    even 0xFFFFFFFF - plus more parked at (0,1,0) and (-5,5,0). The poll picked
    zone 0 there; the correct answer is 5, proven in game. A record whose zone
    does not match its position is culled, so that guess silently lost every
    object placed at the spawn.

    So: drop the invalid zone, drop stacked template records, and when what is
    left still does not agree, fall back to the nearest record whose OWN
    neighbourhood is unanimous - real geometry vouching for itself.
    """
    parked = _parked(d, recs)
    ranked = []
    for s2 in recs:
        q = pos_of(d, s2)
        if q is None:
            continue
        z = u32(d, s2 + ZONE)
        if z == 0xFFFFFFFF:
            continue
        if tuple(round(v, 2) for v in q) in parked:
            continue
        ranked.append((math.dist(q, target), s2, q, z))
    ranked.sort()
    if not ranked:
        return None, 0
    tally = {}
    for _dist, _s2, _q, z in ranked[:k]:
        tally[z] = tally.get(z, 0) + 1
    z = max(tally, key=tally.get)
    # Unanimity or nothing. A 10/12 majority is exactly what the parked
    # records at region_00's spawn produce, and it was wrong - so anything
    # short offull agreement defers to real geometry below.
    if tally[z] >= k:
        return z, tally[z]
    # Weak agreement. Prefer real geometry, but ONLY nearby: the fallback
    # used to walk outwards until it found any record with a unanimous
    # neighbourhood, which in region_03 returned zone 18 from somewhere far
    # away when the records 7 units from the site carried 11 and 12. Nothing
    # spawned at all, because the zone was not merely wrong but foreign.
    near = [t for t in ranked if t[0] <= ranked[0][0] + 25.0]
    for _dist, _s2, q, zz in near:
        t2 = {}
        for _d2, _s3, _q3, z3 in sorted(near, key=lambda rr: math.dist(rr[2], q))[:k]:
            t2[z3] = t2.get(z3, 0) + 1
        best = max(t2, key=t2.get)
        if t2[best] >= k:
            return best, t2[best]
    # still nothing unanimous - the closest record's own zone beats a vote
    # dominated by stacked duplicates
    return ranked[0][3], tally.get(ranked[0][3], 0)


def fresh_id(d, used):
    cand = 0xA73C0001
    while d.find(struct.pack("<I", cand)) >= 0 or cand in used:
        cand += 1
    used.add(cand)
    return cand


def read_rows(path):
    rows = []
    with open(path, newline="", encoding="utf-8-sig") as f:
        for i, r in enumerate(csv.DictReader(f), 2):
            name = (r.get("Prop") or "").strip()
            if not name:
                continue
            try:
                rows.append({
                    "line": i, "prop": name,
                    "zone": (r.get("Zone") or "").strip(),
                    "tint": (r.get("Tint") or "").strip(),
                    "scale": (r.get("Scale") or "").strip(),
                    "x": float(r.get("X") or 0), "y": float(r.get("Y") or 0),
                    "z": float(r.get("Z") or 0),
                    "yaw": float(r.get("Yaw") or 0),
                    "pitch": float(r.get("Pitch") or 0),
                    "roll": float(r.get("Roll") or 0),
                })
            except ValueError:
                print("  line %d: skipped, non-numeric coordinate" % i)
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("region")
    ap.add_argument("--csv")
    ap.add_argument("--base",
                    help="rebuild from THIS file rather than the pristine "
                         "backup. A preset that ships its own .lvl (the AT3 "
                         "Official fight edits, say) is the base the props "
                         "must layer on top of, or one wipes the other.")
    ap.add_argument("--check", action="store_true",
                    help="report what would happen, write nothing")
    ap.add_argument("--list", action="store_true",
                    help="catalogue, with each prop's donor and reach")
    ap.add_argument("--revert", action="store_true")
    a = ap.parse_args()

    # A props CSV can name something that is not a playable region - the data
    # tree has a `utility` bundle folder with no level - and the launcher feeds
    # every props_*.csv it finds. Say so and stop, rather than raising a
    # traceback into the feedback pane.
    if not os.path.exists(lvl_path(a.region)):
        print("region_%s has no level file - nothing to place" % a.region)
        return 0
    p = lvl_path(a.region)

    if a.revert:
        if os.path.exists(p + BAK):
            shutil.copy2(p + BAK, p)
            print("reverted lm_level_%s.lvl to vanilla" % a.region)
        else:
            print("nothing to revert - no %s" % BAK)
        return

    # Always rebuild from a fixed base so the CSV is the whole truth and
    # repeated launches never stack duplicates. The base is the preset's own
    # .lvl when one is supplied, otherwise the pristine backup.
    if not os.path.exists(p + BAK):
        shutil.copy2(p, p + BAK)
    base_path = p + BAK
    if a.base:
        if not os.path.exists(a.base):
            sys.exit("base file not found: %s" % a.base)
        base_path = a.base
    src = open(base_path, "rb").read()
    if base_path != p + BAK:
        print("base: %s" % os.path.basename(base_path))
    d = bytearray(src)
    recs, end = walk(bytes(d))
    dn = donors(bytes(d), recs)          # catalogue only; --list needs it here
    zones, deps = zone_deps(a.region)

    if a.list:
        print("catalogue for region_%s\n" % a.region)
        for name, spec in CATALOGUE.items():
            got = dn.get(name)
            res = spec["residency"]
            if res is None:
                reach = "every zone (normal bundle, not zone-gated)"
            elif res in zones:
                idx = zones.index(res)
                ok = [z for z, dp in enumerate(deps) if idx in dp]
                reach = "%d of %d zones - %s" % (len(ok), len(deps), ok)
            else:
                reach = "bundle %s not in this region" % res
            print("  %-26s key %08X  donor %s" %
                  (name, spec["key"], ("@%d (%d bytes)" % got) if got else "NONE"))
            print("  %-26s reach: %s" % ("", reach))
        return

    if not a.csv:
        ap.print_help()
        return
    if not os.path.exists(a.csv):
        # no list means no props - restore vanilla rather than leaving whatever
        # a previous run put there
        open(p, "wb").write(src)
        print("no placement file: %s - level restored to vanilla" % a.csv)
        return

    rows = read_rows(a.csv)
    reach = library_reach(a.region)
    # Re-scan for donors now that the placements are known, so rows that
    # name their object by raw key get one too.
    dn = donors(bytes(d), recs, extra=[r["prop"] for r in rows])
    print("region_%s: %d placement(s), %d records in chain"
          % (a.region, len(rows), len(recs)))
    if not rows:
        open(p, "wb").write(src)
        print("list is empty - level left vanilla")
        return

    used, applied, skipped, warned = set(), 0, 0, []
    for r in rows:
        spec = resolve(r["prop"])
        if spec is None:
            print("  line %d: unknown prop %r - skipped" % (r["line"], r["prop"]))
            skipped += 1
            continue
        if r["prop"] not in dn:
            print("  line %d: no donor for %r in this region - skipped"
                  % (r["line"], r["prop"]))
            skipped += 1
            continue

        recs, end = walk(bytes(d))
        target = (r["x"], r["y"], r["z"])

        # Nearest donor to THIS placement, re-found every row. Offsets shift as
        # earlier rows are inserted, so it cannot be cached, and the nearest one
        # differs per placement anyway.
        found, ddist = donor_near(bytes(d), recs, spec["key"], target)
        if not found:
            print("  line %d: donor lost - skipped" % r["line"])
            skipped += 1
            continue
        donor, dlen = found
        zone, votes = zone_at(bytes(d), recs, target)
        # An explicit Zone column overrides the poll. The poll reads the zone
        # off the 12 nearest records, which only works where those neighbours
        # are real world geometry. Near region_00 spawn the neighbours are
        # records parked at the origin, so the vote splits across three zones
        # and the guess is arbitrary - and a record whose zone does not match
        # its position is culled wherever its geometry lives.
        if r.get("zone"):
            try:
                zone = int(r["zone"])
                votes = -1
            except ValueError:
                pass
        if zone is None:
            print("  line %d: cannot determine a zone - skipped" % r["line"])
            skipped += 1
            continue

        res = spec["residency"]
        if res is not None and zones and res in zones:
            idx = zones.index(res)
            if zone < len(deps) and idx not in deps[zone]:
                warned.append("%s at (%.1f, %.1f, %.1f) is in zone %d, which "
                              "does not load %s - it will not be visible there"
                              % (r["prop"], target[0], target[1], target[2],
                                 zone, res))
        elif spec["key"] in reach:
            rc = reach[spec["key"]]
            if rc is not None and rc != "?" and zone not in rc:
                warned.append("%s at (%.1f, %.1f, %.1f) is in zone %d, but its "
                              "geometry is only loaded by zone(s) %s - it will "
                              "be placed but NOT visible there"
                              % (r["prop"], target[0], target[1], target[2],
                                 zone, ",".join(str(z) for z in sorted(rc))))

        # nearest record, both as the splice point and for the baked tint
        nearest, best = None, None
        for s in recs:
            q = pos_of(bytes(d), s)
            if q is None:
                continue
            dist = math.dist(q, target)
            if best is None or dist < best:
                nearest, best = s, dist

        place = u32(bytes(d), nearest + NEXT)
        rec = bytearray(d[donor:donor + dlen])
        struct.pack_into("<I", rec, NEXT, place + dlen)
        struct.pack_into("<I", rec, INST_ID, fresh_id(bytes(d), used))
        struct.pack_into("<I", rec, NAME2, 0x2DFD1072)
        struct.pack_into("<I", rec, ZONE, zone)
        for i, v in enumerate(matrix_from_euler(r["yaw"], r["pitch"], r["roll"])):
            struct.pack_into("<f", rec, ROT + 4 * i, v)
        for i, v in enumerate(target):
            struct.pack_into("<f", rec, POS + 4 * i, v)
        # TINT: an explicit colour beats inheriting the neighbour's.
        #
        # +77 is a per-instance RGBA. Vanilla region_01 uses 1432 distinct
        # values across the full 0..255 range (mean ~120), with alpha only ever
        # 254 or 255 - so the first three bytes are a colour and the fourth is
        # not really an alpha channel.
        #
        # Copying it from the nearest record approximates the local lighting,
        # which is the right default. But a copied prop has no baked component
        # for the tint to modulate, so it renders at the raw tint - a pale
        # 94a9c4 neighbour reads as "impossibly bright". Setting it explicitly
        # lets a placement be darkened to match its surroundings without any
        # baked data at all.
        #
        # THE FIELD IS BGRA, NOT RGBA - MEASURED.
        #
        # Writing FF 00 00 FF intending red produced NEON BLUE debris in game.
        # Read as B=FF, G=00, R=00 that is exactly pure blue, so the stored
        # order is blue, green, red, alpha. Every vanilla value is consistent
        # with this too: the common 5f4e47 reads as a warm brown either way,
        # which is why the order stayed hidden until a saturated colour was
        # used.
        #
        # THE CSV TAKES BGRA AND WRITES IT VERBATIM.
        #
        # No reversal. The column is labelled BGRA in the Prop Editor so the
        # order is stated where it is typed, rather than being silently
        # translated somewhere the user cannot see.
        #
        # Red is therefore 0000FF, not FF0000. Only ONE data point is actually
        # confirmed in game: stored FF 00 00 FF rendered NEON BLUE. That the
        # opposite produces red is the obvious inference but has not been
        # observed, so it is being tested rather than assumed.
        # SCALE at +73. Uniform only - the 3x3 at +25 is a pure rotation in
        # every one of the game's 22,962 placed records (row norms exactly 1.0,
        # zero deviation), so there is nowhere for a per-axis scale to live and
        # nothing in the game uses one.
        #
        # With no Scale column the donor's own scale is inherited, which is why
        # cloning a 4.372x Wolvark gun gives you a 4.372x gun.
        if r.get("scale"):
            try:
                sc = float(r["scale"])
                if sc <= 0:
                    raise ValueError("must be positive")
                struct.pack_into("<f", rec, ONE, sc)
            except ValueError as e:
                print("  line %d: bad Scale %r - %s" % (r["line"], r["scale"], e))

        explicit = None
        if r.get("tint"):
            t = r["tint"].strip().lstrip("#")
            if len(t) in (6, 8):
                try:
                    explicit = bytes.fromhex(t if len(t) == 8 else t + "ff")
                except ValueError:
                    explicit = None
            if explicit is None:
                print("  line %d: bad Tint %r - expected BGRA as BBGGRR or BBGGRRAA"
                      % (r["line"], r["tint"]))
        if explicit is not None:
            rec[TINT:TINT + 4] = explicit
        elif u32(bytes(d), nearest + NEXT) - nearest > TINT + 4:
            rec[TINT:TINT + 4] = d[nearest + TINT:nearest + TINT + 4]

        out = bytearray(bytes(d)[:place]) + rec + bytearray(bytes(d)[place:])
        cur = bytes(d)
        for s in recs:
            moved = s if s < place else s + dlen
            v = u32(cur, s + NEXT)
            struct.pack_into("<I", out, moved + NEXT,
                             v if v < place else v + dlen)
        struct.pack_into("<I", out, nearest + NEXT, place)
        d = out
        applied += 1
        warn = "  << donor far, may not light" if ddist and ddist > 60 else ""
        sc = struct.unpack_from("<f", rec, ONE)[0]
        print("  %-26s (%8.2f,%8.2f,%7.2f) yaw %6.1f  scale %.3g  zone %-3d  donor %.0fu%s"
              % (r["prop"], target[0], target[1], target[2], r["yaw"], sc, zone,
                 ddist or 0, warn))

    if a.check:
        print("\ncheck only - nothing written")
        open(p, "wb").write(src)
    else:
        open(p, "wb").write(bytes(d))

    # re-walk what is now on disk; a broken chain must never reach the game
    chk = open(p, "rb").read()
    r2, e2 = walk(chk)
    bad = sum(1 for i, s in enumerate(r2)
              if u32(chk, s + NEXT) != (r2[i + 1] if i + 1 < len(r2) else e2))
    ok = (u32(chk, e2) == SENTINEL and bad == 0 and r2 == sorted(r2))
    print("\n%d %s, %d skipped. chain on disk: %d records, %d non-contiguous, "
          "terminator %08X -> %s"
          % (applied, "would apply" if a.check else "applied",
             skipped, len(r2), bad, u32(chk, e2),
             "OK" if ok else "BROKEN"))
    if not ok and not a.check:
        shutil.copy2(p + BAK, p)
        print("chain did not verify - reverted to vanilla, nothing applied")
    for w in warned:
        print("  WARNING: %s" % w)


if __name__ == "__main__":
    main()
